apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fastapi
    tier: frontend
  name: web-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
      tier: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fastapi
        tier: frontend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: REDIS_CACHE_HOST
          value: "redis-master"
        - name: PORT
          value: "5000"
        image: asia-southeast1-docker.pkg.dev/employme-332505/employme/employme-app
        name: web-fastapi
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
status: {}