apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi
    tier: frontend
  name: web-fastapi-ip
spec:
  selector:
    app: fastapi
    tier: frontend
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: "34.136.193.82"